<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
  <ol class="carousel-indicators ">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <?php
    $counter=0;
    foreach ($this->new_products as $key => $value) 
     {
        if($counter==0)
        {
    ?>
        <div class="item active">
            <img class="img-responsive center-block" src="<?= $value['photo']?>" alt="<?=$value['name_en']?>">
            <div class="carousel-caption">
             <?= $value['description_en'] ?>
            </div>
        </div>
      <?php
        }
        else
        {
       ?>
        <div class="item">
            <img src="<?= $value['photo']?>" alt="<?=$value['name_en']?>">
            <div class="carousel-caption">
             <?= $value['description_en'] ?>
             </div>
         </div>
      <?php
        }
     $counter++;
     }
        ?>
  </div>

  <!-- Controls -->
</div>
<!------------------------------------------------------------------>
<div class="container">
  <div class="row">
      <?php
       foreach ($this->all_categories_ctx as $key => $value) 
        {
        ?>
  <div class="col-sm-4 col-md-4" >
    <div class="thumbnail">
      <img src="<?= $value['photo']?>" alt="<?=$value['name']?>" class="img-circle">
      <div class="caption">
        <h3><?=$value['name']?></h3>
        <p><center><a href="#" class="btn btn-primary" role="button">View Category Products</a></center></p>
      </div>
    </div>
  </div>
      <?php
        }
        ?>
</div> 
</div>    