<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
  <ol class="carousel-indicators ">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <?php
    $counter=0;
    foreach ($this->new_products as $key => $value) 
     {
        if($counter==0)
        {
    ?>
        <div class="item active">
            <img class="img-responsive center-block" src="<?= $value['photo']?>" alt="<?=$value['name_en']?>">
            <div class="carousel-caption">
             <?= $value['description_en'] ?>
            </div>
        </div>
      <?php
        }
        else
        {
       ?>
        <div class="item">
            <img src="<?= $value['photo']?>" alt="<?=$value['name_en']?>">
            <div class="carousel-caption">
             <?= $value['description_en'] ?>
             </div>
         </div>
      <?php
        }
     $counter++;
     }
        ?>
  </div>

  <!-- Controls -->
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!------------------------------------------------------------------>

<div id="searchResult"></div>

<?php
$counter = 0;
foreach ($this->all_categories_ctx as $category) {
    if (!($counter % 3)) {
        echo '<div class="row">';
    }
    ?>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="<?= $category['photo'] ?>">
            <div class="caption">
                <h3><?= $category['name'] ?></h3>
                <p>
                    <a href="/products/display/cid/<?= $category['id'] ?>" class="btn btn-primary" role="button">View Category Products</a>
                </p>
            </div>
        </div>
    </div>
    <?php
    if (!(($counter - 2) % 3)) {
        echo "</div>";
    }
    $counter += 1;
}
?>