<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="<?= $this->baseUrl()?>/assets/node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= $this->baseUrl()?>/assets/css/style.css"/>
    <script type="text/javascript" src="<?= $this->baseUrl()?>/assets/node_modules/tether/dist/js/tether.min.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl()?>/assets/node_modules/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl()?>/assets/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <title>E-Commerce</title>
</head>
<body>
<?php echo $this->layout()->content; ?>
</body>
</html>
