<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="<?= $this->baseUrl() ?>/assets/node_modules/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?= $this->baseUrl() ?>/assets/css/style.css"/>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/assets/node_modules/tether/dist/js/tether.min.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/assets/node_modules/jquery/dist/jquery.min.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/assets/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
        <title>E-Commerce</title>
    </head>
    <!-- #################################################################### -->
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">E-commerce Platform</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Departments <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <?php
                                foreach ($this->all_categories_ctx as $key => $value) {
                                    ?>
                                    <li><a href="category/category_id/<?= $value['id'] ?>"><?= $value['name'] ?></a></li>
                                    <?php
                                }
                                ?>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Login</a></li>
                        <li><a href="#">Register</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>

        <?php echo $this->layout()->content; ?>  
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/assets/js/script.js"></script>
    </body>
    <div class="footer">
        <div class="wrap">
            <div class="foot-links">
                <ul>
                    <h3>Links</h3>
                    <li><a href="<?= $this->baseUrl() ?>">Home</a></li>
                    <li><a href="<?= $this->baseUrl() ?>/products">Products</a></li>
                    <li><a href="//w3layouts.com/contact" >Contact Us</a></li>
                </ul>
                <ul>
                    <h3>Others</h3>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">Support</a></li>
                </ul>

                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>


    </div>
</div>
</html>
