<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center>Products Page</center></h1>
  </div>
	<div class="panel-body">


    <div class="row">

      <?php  $language='en'; $count=1; $j=1?>
      <?php foreach ($this->all_products_with_offer as $key => $value) : ?>
                <div class="col-sm-6 col-md-4" >
                  <div class="thumbnail">
                    <a href='/products/details/product_id/<?=$value['id']?>'><img src="<?= $value['photo'] ?>" alt='Smiley face' height='400' width='300' class="img-circle"></a>
                    <div class="caption">
                      <h3><center><?php if($language=='en') echo $value['name_en']; else echo $value['name_ar']?></center></h3>
                      <p><center><?php  if($language=='en') echo $value['description_en'];  else echo $value['description_ar']?></center></p>
                      <p><label>Price:  </label><?= " ".$value['unit_price']." L.E." ?></p>
                      <?php if($value['discount']) :?>
                      <p><label>discount:  </label><?= " ".$value['discount']." %" ?></p>
                    <?php endif ; ?>
                      <p>
                        <div class="fixedRate">
                          <?php for ($i=5; $i >=1 ; $i--) :?>
                            <?php if($value['rate']==$i): ?>
                            <input disabled="true" class='radio1' type="radio" value=<?=$i?>  checked="checked"/>
                            <label for="star<?=$i?>" ><?=$i?> stars</label>
                          <?php else : ?>
                            <input  disabled="true" class='radio1' type="radio" value=<?=$i?>/>
                            <label for="star<?=$i?>" ><?=$i?> stars</label>
                          <?php endif; ?>
                          <?php endfor; ?>
                        </div>
                      </p>
                    </div>
                  </div>
                </div>
                <?php $count++; if ($count>=3*$j) {
                  // echo $count."<br>".$j;
                  $j++; echo "</div><div class='row'>";
                } ?>
              <?php endforeach; ?>

	</div>
</div>
</div>
