<?php

if(isset($_GET['ar'])){
    $language="ar";
}else {
  $language="en";
}

?>



		<div id="wrapper" class="container">
<hr><a class="btn btn-warning" href="/shop/add">add product</a>
			<section class="header_text sub">
				<h4><span>Products</span></h4>
			</section>
			<section class="main-content">

				<div class="row">
					<div class="span9">
						<ul class="thumbnails listing-products">
              <?php
$counter = 0;
foreach ($this->all_productsByVendor as $value ) {
    if (!($counter % 3)) {
        echo '<div class="row">';
    }
    ?>
							<li class="span3">
								<div class="product-box">
									<span class="sale_tag"></span>
									<a href="/shop/details/product_id/<?= $value['id'] ?>"><img class="imageDisplay" alt="" src="<?= $value['photo'] ?>"></a><br/>
                  <?php if($language=="en") : ?>
                    <a href="/shop/details/product_id/<?= $value['id'] ?>" class="title"><?= $value['name_en'] ?></a><br/>
                  <?php else: ?>
                    <a href="/shop/details/product_id/<?= $value['id'] ?>" class="title"><?= $value['name_ar'] ?></a><br/>
                  <?php endif; ?>
                  <?php if ($value['discount']) : ?>
                                <a class="category"><?= "discount ".$value['discount'] . " %" ?></a>
                  <?php endif; ?>
                  <p class="price"><?= " " . $value['unit_price'] . " L.E." ?></p>

                  <p>
                            <div class="fixedRate">
                                <?php for ($i = 5; $i >= 1; $i--) : ?>
                      <?php if ($value['rate'] == $i): ?>
                                        <input disabled="true" class='radio1' type="radio" value=<?= $i ?>  checked="checked"/>
                                        <label for="star<?= $i ?>" ><?= $i ?> stars</label>
                      <?php else : ?>
                                        <input  disabled="true" class='radio1' type="radio" value=<?= $i ?>/>
                                        <label for="star<?= $i ?>" ><?= $i ?> stars</label>
                      <?php endif; ?>
                    <?php endfor; ?>
                            </div></p>
                    <a href="#" class="dropdown-toggle btn btn-success" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add Product <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?= $this->baseUrl() ?>/wishlist/add-item-to-wishlist/product_id/<?= $value['id'] ?>">Add To Wishlist </a></li>
                                <li><a href="<?= $this->baseUrl() ?>/shoppingcart/additemtocart/product_id/<?= $value['id'] ?>">Add To Cart </a></li>
                            </ul>
								</div>
							</li>
              <?php
    if (!(($counter - 2) % 3)) {
        echo "</div>";
    }
    $counter += 1;
}
?>
						</ul>
						<hr>
						<div class="pagination pagination-small pagination-centered">
							<ul>
								<li><a href="#">Prev</a></li>
								<li class="active"><a href="#">1</a></li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">4</a></li>
								<li><a href="#">Next</a></li>
							</ul>
						</div>
					</div>
					<div class="span3 col" style="width:250px">
						<div class="block">
							<ul class="nav nav-list">
								<li class="nav-header">SUB CATEGORIES</li>
								<li><a href="#">Nullam semper elementum</a></li>
								<li class="active"><a href="#">Phasellus ultricies</a></li>
								<li><a href="#">Donec laoreet dui</a></li>
								<li><a href="#">Nullam semper elementum</a></li>
								<li><a href="#">Phasellus ultricies</a></li>
								<li><a href="#">Donec laoreet dui</a></li>
							</ul>
							<br/>
							<ul class="nav nav-list below">
								<li class="nav-header">MANUFACTURES</li>
								<li><a href="#">Adidas</a></li>
								<li><a href="#">Nike</a></li>
								<li><a href="#">Dunlop</a></li>
								<li><a href="#">Yamaha</a></li>
							</ul>
						</div>
						<div class="block">
							<h4 class="title">
								<span class="pull-left"><span class="text">Randomize</span></span>
								<span class="pull-right">
									<a class="left button" href="#myCarousel" data-slide="prev"></a><a class="right button" href="#myCarousel" data-slide="next"></a>
								</span>
							</h4>
							<div id="myCarousel" class="carousel slide">
								<div class="carousel-inner">
									<div class="active item">
										<ul class="thumbnails listing-products">
											<li class="span3">
												<div class="product-box">
													<span class="sale_tag"></span>
													<img alt="" src="<?= $this->baseUrl() ?>/assets/themes/images/ladies/1.jpg"><br/>
													<a href="product_detail.html" class="title">Fusce id molestie massa</a><br/>
													<a href="#" class="category">Suspendisse aliquet</a>
													<p class="price">$261</p>
												</div>
											</li>
										</ul>
									</div>
									<div class="item">
										<ul class="thumbnails listing-products">
											<li class="span3">
												<div class="product-box">
													<img alt="" src="<?= $this->baseUrl() ?>/assets/themes/images/ladies/2.jpg"><br/>
													<a href="product_detail.html" class="title">Tempor sem sodales</a><br/>
													<a href="#" class="category">Urna nec lectus mollis</a>
													<p class="price">$134</p>
												</div>
											</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
						<div class="block">
							<h4 class="title"><strong>Best</strong> Seller</h4>
							<ul class="small-product">
								<li>
									<a href="#" title="Praesent tempor sem sodales">
										<img src="<?= $this->baseUrl() ?>/assets/themes/images/ladies/3.jpg" alt="Praesent tempor sem sodales">
									</a>
									<a href="#">Praesent tempor sem</a>
								</li>
								<li>
									<a href="#" title="Luctus quam ultrices rutrum">
										<img src="<?= $this->baseUrl() ?>/assets/themes/images/ladies/4.jpg" alt="Luctus quam ultrices rutrum">
									</a>
									<a href="#">Luctus quam ultrices rutrum</a>
								</li>
								<li>
									<a href="#" title="Fusce id molestie massa">
										<img src="<?= $this->baseUrl() ?>/assets/themes/images/ladies/5.jpg" alt="Fusce id molestie massa">
									</a>
									<a href="#">Fusce id molestie massa</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</section>
			<section id="footer-bar">
				<div class="row">
					<div class="span3">
						<h4>Navigation</h4>
						<ul class="nav">
							<li><a href="./index.html">Homepage</a></li>
							<li><a href="./about.html">About Us</a></li>
							<li><a href="./contact.html">Contac Us</a></li>
							<li><a href="./cart.html">Your Cart</a></li>
							<li><a href="./register.html">Login</a></li>
						</ul>
					</div>
					<div class="span4">
						<h4>My Account</h4>
						<ul class="nav">
							<li><a href="#">My Account</a></li>
							<li><a href="#">Order History</a></li>
							<li><a href="#">Wish List</a></li>
							<li><a href="#">Newsletter</a></li>
						</ul>
					</div>
					<div class="span5">
						<p class="logo"><img src="<?= $this->baseUrl() ?>/assets/themes/images/logo.png" class="site_logo" alt=""></p>
						<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. the  Lorem Ipsum has been the industry's standard dummy text ever since the you.</p>
						<br/>
						<span class="social_icons">
							<a class="facebook" href="#">Facebook</a>
							<a class="twitter" href="#">Twitter</a>
							<a class="skype" href="#">Skype</a>
							<a class="vimeo" href="#">Vimeo</a>
						</span>
					</div>
				</div>
			</section>
			<section id="copyright">
				<span>Copyright 2013 bootstrappage template  All right reserved.</span>
			</section>
		</div>
		<script src="<?= $this->baseUrl() ?>/assets/themes/js/common.js"></script>
