<!--<ul class="nav nav-tabs nav-justified">
    <li role="presentation" class="active"><a href="users">Manage Users</a></li>
    <li role="presentation"><a href="categories">Manage Categories</a></li>
</ul>-->

<div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist">
        <li role="presentation" class="active"><a href="#users" aria-controls="users" role="tab" data-toggle="tab">Manage Users</a></li>
        <li role="presentation"><a href="#cat" aria-controls="cat" role="tab" data-toggle="tab">Manage Categories</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="users">
            <table class="table table-striped table-bordered">
                <th>#</th><th>Full Name</th><th>E-Mail</th><th colspan="2">Actions</th>
                <?php
                foreach ($this->users as $user) {
                    ?> 
                    <tr>
                        <td><?= $user['id'] ?></td>
                        <td><?= $user['fullname'] ?></td>
                        <td><?= $user['email'] ?></td>
                        <td>
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myid<?= $user['id'] ?>">Send Coupon</button>

                            <div class="modal fade bs-example-modal-sm" id="myid<?= $user['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                <div class="modal-dialog modal-sm" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title">Sending coupon to a customer:</h4>
                                        </div>
                                        <form class="form-inline" method="post" action="coupon/uid/<?= $user['id'] ?>">
                                            <div class="modal-body">
                                                <div class="form-group">
                                                    <label for="discount">Discount Amount</label>
                                                    <input type="text" class="form-control" id="discount" name="discount">
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                                <button type="submit" class="btn btn-primary">Send</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <?php
                        // Check to see the user state (active/inactive) in order to 
                        // display the right action, block or activate the user.
                        $isActive = ($user['isactive'] == 1) ? ["block", "danger"]: ["activate", "success"];
                        ?>
                        <td>
                            <a class="btn btn-<?= $isActive[1] ?>" href="/admin/<?= $isActive[0] ?>/uid/<?= $user['id'] ?>">
                                <?= ucfirst($isActive[0]) ?> <!-- ucfirst() captalizes the first letter.-->
                            </a>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </table>

        </div>
        <div role="tabpanel" class="tab-pane fade" id="cat">
            <a class="btn btn-lg btn-block btn-primary" style="margin: 20px" href="/admin/addcat"><span class="glyphicon glyphicon-plus"></span>Add Category</a>
            <?php
            $counter = 0;
            foreach ($this->categories as $category) {
                if (!($counter % 3)) {
                    echo '<div class="row">';
                }
                ?>

                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img src="<?= $category['photo'] ?>">
                        <div class="caption">
                            <h3><?= $category['name'] ?></h3>
                            <p>
                                <a href="/admin/editcat/cat_id/<?= $category['id'] ?>" class="btn btn-success" role="button">Edit</a>
                                <a href="/admin/delcat/cat_id/<?= $category['id'] ?>" class="btn btn-danger" role="button">Delete</a>
                            </p>
                        </div>
                    </div>
                </div>
                <?php
                if (!(($counter - 2) % 3)) {
                    echo "</div>";
                }
                $counter += 1;
            }
            ?>
        </div>
    </div>

</div>