<table class="table table-striped table-bordered">
    <th>#</th><th>Full Name</th><th>E-Mail</th><th colspan="2">Actions</th>
<?php 
foreach ($this->users as $user) {
?> 
    <tr>
        <td><?=$user['id']?></td>
        <td><?=$user['fullname']?></td>
	<td><?=$user['email']?></td>
        <td>
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myid<?=$user['id']?>">Send Coupon</button>

            <div class="modal fade bs-example-modal-sm" id="myid<?=$user['id']?>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                <div class="modal-dialog modal-sm" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">Sending coupon to a customer:</h4>
                        </div>
                        <form class="form-inline" method="post" action="coupon/uid/<?=$user['id']?>">
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="discount">Discount Amount</label>
                                <input type="text" class="form-control" id="discount" name="discount">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Send</button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </td>
        <?php
        // Check to see the user state (active/inactive) in order to 
        // display the right action, block or activate the user.
        $isActive = ($user['isactive'] == 1) ? "block" : "activate";
        ?>
        <td>
            <a class="btn btn-danger" href="<?=$isActive?>/uid/<?=$user['id']?>">
                <?=ucfirst($isActive)?> <!-- ucfirst() captalizes the first letter.-->
            </a>
        </td>
    </tr>
 <?php
}
?>
</table>
