<section class="main-content">        
    <div class="row">
        <div class="span9">         
            <h4 class="title"><span class="text"><strong>My</strong> Wishlist (<?php echo sizeof($this->mywishlist_items_ctx); ?>) </span></h4>
           <?php 
           if (sizeof($this->mywishlist_items_ctx==0)){?>
               <h3>No Wish List Items</h3>
               <?php
           }else{?>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Product Name</th>
                        <th>Image</th>
                        <th>Remove</th>
                        <th>Add To Cart</th>
                    </tr>
                </thead>
                <tbody>

                    <?php
                    
                    $language = 'ar';
                    foreach ($this->mywishlist_items_ctx as $key => $value) {
                        ?>
                        <tr>
                            <td>
                                <?php if ($language == 'en') {
                                    ?><?= $value['name_en'] ?><?php } else { ?><?= $value['name_ar'] ?><?php } ?>
                            </td>
                            <td>
                                <img style="max-height: 100px !important;" src='<?= $value['photo'] ?>'>
                            </td>    
                            <td><a class='btn btn-danger' href='delete-wishlist-item/product_id/<?= $value['product_id'] ?>'>Remove Product</a>
                            </td>
                            <td><a class='btn btn-warning' href='<?= $this->baseUrl() ?>/shoppingcart/additemtocart/product_id/<?= $value['product_id'] ?>'>Add to Cart</a></td>
                        </tr>
                        <?php
                    }
                    ?>


                </tbody>
            </table>
              <?php
           }
           ?>
        </div>
        <div class="span3 col">
            <div class="block">	
                <ul class="nav nav-list">
                    <li class="nav-header">CATEGORIES</li><?php
                    foreach($this->all_categories as $key=>$value){?>
                    
                    <li><a href="/products/display/cid/<?=$value['id']?>"><?=$value['name']?></a></li>
                  <?php
                    }
                    ?>
                </ul>
                <br/>
            
            </div>
            <div class="block">
                <h4 class="title">
                    <span class="pull-left"><span class="text">Randomize</span></span>
                    <span class="pull-right">
                        <a class="left button" href="#myCarousel" data-slide="prev"></a><a class="right button" href="#myCarousel" data-slide="next"></a>
                    </span>
                </h4>
                <div id="myCarousel" class="carousel slide">
                    <div class="carousel-inner">
                        <div class="active item">
                            <ul class="thumbnails listing-products">
                                <li class="span3">
                                    <div class="product-box">
                                        <span class="sale_tag"></span>												
                                        <a href="product_detail.html"><img alt="" src="themes/images/ladies/2.jpg"></a><br/>
                                        <a href="product_detail.html" class="title">Fusce id molestie massa</a><br/>
                                        <a href="#" class="category">Suspendisse aliquet</a>
                                        <p class="price">$261</p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="item">
                            <ul class="thumbnails listing-products">
                                <li class="span3">
                                    <div class="product-box">												
                                        <a href="product_detail.html"><img alt="" src="themes/images/ladies/4.jpg"></a><br/>
                                        <a href="product_detail.html" class="title">Tempor sem sodales</a><br/>
                                        <a href="#" class="category">Urna nec lectus mollis</a>
                                        <p class="price">$134</p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>						
        </div>

</section>			
<section id="footer-bar">
    <div class="row">
        <div class="span3">
            <h4>Navigation</h4>
            <ul class="nav">
                <li><a href="./index.html">Homepage</a></li>  
                <li><a href="./about.html">About Us</a></li>
                <li><a href="./contact.html">Contac Us</a></li>
                <li><a href="./cart.html">Your Cart</a></li>
                <li><a href="./register.html">Login</a></li>							
            </ul>					
        </div>
        <div class="span4">
            <h4>My Account</h4>
            <ul class="nav">
                <li><a href="#">My Account</a></li>
                <li><a href="#">Order History</a></li>
                <li><a href="#">Wish List</a></li>
                <li><a href="#">Newsletter</a></li>
            </ul>
        </div>
        <div class="span5">
            <p class="logo"><img src="themes/images/logo.png" class="site_logo" alt=""></p>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. the  Lorem Ipsum has been the industry's standard dummy text ever since the you.</p>
            <br/>
            <span class="social_icons">
                <a class="facebook" href="#">Facebook</a>
                <a class="twitter" href="#">Twitter</a>
                <a class="skype" href="#">Skype</a>
                <a class="vimeo" href="#">Vimeo</a>
            </span>
        </div>					
    </div>	
</section>
<section id="copyright">
    <span>Copyright 2013 bootstrappage template  All right reserved.</span>
</section>
</div>
<script src="themes/js/common.js"></script>
<script>
    $(document).ready(function () {
        $('#checkout').click(function (e) {
            document.location.href = "checkout.html";
        })
    });
</script>		
</body>
</html>