<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center>reviews Page</center></h1>
  </div></div>


<div class="container">
	<table class="table" border="1">
	  <th>user ID</th><th>product ID</th><th>rate</th><th>comment</th><th colspan="3" ><center>actions</center></th>


	 <?php

	foreach ($this->all_reviews as $key => $value) {
	  echo "<tr><td>".$value['user_id']."</td><td>".$value['product_id']."</td><td>".$value['rate']."</td><td>".$value['comment']."</td><td><center><a class='btn btn-primary' href='details?uid=".$value['user_id']."&pid=".$value['product_id']."'>details</a></center></td><td><center><a class='btn btn-danger' href='delete?uid=".$value['user_id']."&pid=".$value['product_id']."'>delete</a><center></td></tr>";
	}
	 ?>

	</table>

</div>

<!-- <td><center><a class='btn btn-primary' href='details/cid/".$value['id']."'>details</a></center></td><td><center><a class='btn btn-danger' href='delete/cid/".$value['id']."'>delete</a><center></td> -->
