
<div class="container">

<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center><?php

echo $this->cat_data['id']." ".$this->cat_data['name'];

     ?></center></h1>
  </div>
    <div class="panel-body">
      <table class="table">
      <?php
      echo "<tr><th>id</th><td>".$this->cat_data['id']."</td></tr><tr><th>name</th><td>".$this->cat_data['name']."</td></tr><tr><th>id</th><td>".$this->cat_data['id']."</td></tr>";
      ?>
      </table>
    </div>
</div>
</div>
