<section class="main-content">
  <div class="row">
    <div class="span9">
      <h4 class="title"><span class="text"><strong>Your</strong> Cart (<?php echo sizeof($this->all_cart_details); ?>) </span></h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Remove</th>
            <th>Image</th>
            <th>Product Name</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>

</style>
        <?php
        foreach ($this->all_cart_details as $key => $value) {
        ?>
          <tr>
            <td>
                <a class="btn btn-danger btn-lg" href="removeitemfromcart?shopping_cart_det_id=<?= $value['shopping_cart_det_id']?>" role="button"> Remove </a>
                <input id="shoppingcartid" type="hidden" value="<?= $value['shopping_cart_det_id'];?>" />
            </td>
            <td><a href="/products/details/product_id/ <?= $value['id'] ?>"><img  alt="" src="<?= $value['photo'] ?>" class="imageofshoppingcart"></a></td>
            <td><?= $value['name_en'] ?> (<?= $value['description_en'] ?> )</td>


            <td>
                <!-- <input type="text" placeholder="1" class="input-mini"> -->
                <select class="quantity_cell input-mini" id="<?= $value['shopping_cart_det_id'] ?>" onchange="quantitychanged.call(this,event);" >
                <option value="1" <?=$value['quantity'] == '1' ? ' selected="selected"' : '';?>>1</option>
                <option value="2" <?=$value['quantity'] == '2' ? ' selected="selected"' : '';?>>2</option>
                <option value="3" <?=$value['quantity'] == '3' ? ' selected="selected"' : '';?>>3</option>
                <option value="4" <?=$value['quantity'] == '4' ? ' selected="selected"' : '';?>>4</option>
                <option value="5" <?=$value['quantity'] == '5' ? ' selected="selected"' : '';?>>5</option>
            </select>
            </td>
            <td class="price_cell"><?= $value['unit_price'] ?> LE</td>
            <td class="extended_price_cell"><?= $value['unit_price'] * $value['quantity'] ?> LE</td>
          </tr>

        <?php
        }
        ?>
          <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
              <?php if($this->all_cart_details) :?>
            <td><strong><span id="total_cart_cell"><?= $this->all_cart_details[0]['due_amount'] ?> </span>LE</strong></td>
          <?php endif; ?>
          </tr>
        </tbody>
      </table>
      <hr>
        <?php if($this->all_cart_details) :?>
      <p class="cart-total right">
        <strong>Sub-Total</strong>: <span id="sub_total_call"> <?= $this->all_cart_details[0]['due_amount'] ?> </span> LE<br>
        <strong>Discount Amount</strong>: <span id="discount_total_call"> <?= $this->all_cart_details[0]['discount'] ?> </span> LE<br>
        <strong>Total</strong>: <span id="total_cart_cell_bottom"> <?= $this->all_cart_details[0]['total_amount'] ?> </span> LE<br>
      </p>
    <?php else : ?>
      <p><strong>Shopping Cart is empty!</strong></p>
    <?php endif; ?>
      <hr/>
      <p class="buttons center">
        <button type="button" class="btn btn-inverse" data-toggle="modal" data-target="#CheckOutModal">Check Out Now..</button>
      </p>
    </div>


    <div class="span3 col">
      <div class="block">
        <ul class="nav nav-list">
          <li class="nav-header">SUB CATEGORIES</li>
          <li><a href="#">Nullam semper elementum</a></li>
          <li class="active"><a href="#">Phasellus ultricies</a></li>
          <li><a href="#">Donec laoreet dui</a></li>
          <li><a href="#">Nullam semper elementum</a></li>
          <li><a href="#">Phasellus ultricies</a></li>
          <li><a href="#">Donec laoreet dui</a></li>
        </ul>
        <br/>
        <ul class="nav nav-list below">
          <li class="nav-header">MANUFACTURES</li>
          <li><a href="#">Adidas</a></li>
          <li><a href="#">Nike</a></li>
          <li><a href="#">Dunlop</a></li>
          <li><a href="#">Yamaha</a></li>
        </ul>
      </div>
      <div class="block">
        <h4 class="title">
          <span class="pull-left"><span class="text">Randomize</span></span>
          <span class="pull-right">
            <a class="left button" href="#myCarousel" data-slide="prev"></a><a class="right button" href="#myCarousel" data-slide="next"></a>
          </span>
        </h4>
        <div id="myCarousel" class="carousel slide">
          <div class="carousel-inner">
            <div class="active item">
              <ul class="thumbnails listing-products">
                <li class="span3">
                  <div class="product-box">
                    <span class="sale_tag"></span>
                    <a href="product_detail.html"><img alt="" src="themes/images/ladies/2.jpg"></a><br/>
                    <a href="product_detail.html" class="title">Fusce id molestie massa</a><br/>
                    <a href="#" class="category">Suspendisse aliquet</a>
                    <p class="price">$261</p>
                  </div>
                </li>
              </ul>
            </div>
            <div class="item">
              <ul class="thumbnails listing-products">
                <li class="span3">
                  <div class="product-box">
                    <a href="product_detail.html"><img alt="" src="themes/images/ladies/4.jpg"></a><br/>
                    <a href="product_detail.html" class="title">Tempor sem sodales</a><br/>
                    <a href="#" class="category">Urna nec lectus mollis</a>
                    <p class="price">$134</p>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>



<!-- Modal -->
<div id="CheckOutModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Check Out Your Shopping Cart</h4>
      </div>
      <div class="modal-body">
        <div class="show-msg"></div>
        <p>
        <?php

       $total_amount = $this->all_cart_details[0]["total_amount"];
       $total_discount = $this->all_cart_details[0]["discount"];
       $net_amount = $this->all_cart_details[0]["total_amount"] - $this->all_cart_details[0]["discount"];

        ?>
      <div class="form-group">
        <label for="totalAmount"><b>Total Amount :</b> <?= $total_amount ?></label>
      </div>

      <div class="form-group">
        <label for="discount"><b>Discount from Offer :</b> <?= $total_discount ?></label>
      </div>


      <div class="form-group">
        <label for="dueamount"><b>Net Amount :</b> <?= $net_amount ?></label>
      </div>
      <input type="hidden" id="coupon_id" name="coupon_id">
      <div class="form-group">
        <label for="discount"><b>Due Amount (After Coupon) :</b>
        <span id="total_amount_after_coupon" > <?= $net_amount ?></span></label>
      </div>
        <input type="text" id="coupon" name="coupon" class="form-control input-xlarge" placeholder="OR Use a Coupon">
      </div>


      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        <button id="verifybutton" type="button" class="btn btn-default" onclick="verifycoupon()" >Verify</button>

        <a onclick="paybillwithemail()" id="confirmCheckOut" href="" class="btn btn-primary"> Confirm Checkout </a>
      </div>
    </div>

  </div>
</div>
<!-- Modal div end -->
 <script type="text/javascript" src="<?= $this->baseUrl() ?>/assets/js/shoppingcart.js"></script>
