<br /><br />
<!-- <div id="view-content">
	<p>View script for controller <b>Shoppingcart</b> and script/action name <b>mycart</b></p>
</div> -->



<!DOCTYPE html>
<html>
<head>		


	<title></title>
</head>
<body>
<div class="container">

	<h1> Shopping Cart (<?php echo sizeof($this->all_cart_details); ?>)</h1>
	<br/>




	<?php 
	foreach ($this->all_cart_details as $key => $value) {
		echo '<div class="jumbotron">';
		echo '<h2>' . $value['name_en'] .'</h2>';
		echo '<p>' . $value['description_en'] . '</p>';
		echo '<p><a class="btn btn-primary btn-lg" href="productdetails?product_id=' . $value['product_id']. '"'. ' role="button">' . 'Go to product details' . '</a>'  ;


		echo '<p><a class="btn btn-danger btn-lg" href="removeitemfromcart?shopping_cart_det_id=' . $value['shopping_cart_det_id']. '"'. ' role="button">' . 'Remove Item Cart' . '</a>'  ;


		echo '<p> Quantity: <input type="text" value="'.$value['quantity'].'"'. '/></p>';
		echo '</div>';
	}
 
 	echo '<p><a class="btn btn-default btn-lg" href="checkout" role="button"> Check Out </a>'  ;

	?>
</div>
<!-- 

<?php
        var_dump($this->all_cart_details);

?> -->


</body>
</html>
